# hey emacs, this is -*- python -*-

Import('env');

dbdriver = env.get('DBDRIVER', 'mysql')
cxxflags = env.get('CXXFLAGS', '')
twitter = env.get('TWITTER', True)
cxxflags = env.get('CXXFLAGS', '')
if twitter:
  cxxflags.append('-DTWITTER')
cxxflags.append('-DDB_MYSQL' if dbdriver == 'mysql' else '-DDB_SQLITE')
makelib = env.StaticLibrary if env.get('LIBTYPE', '') == 'static' else env.SharedLibrary



# library targets
libcmd=makelib(target='cmd', source=Glob('cmd/*.cc'))
libdisc=makelib(target='disc', source=Glob('disc/*.cc'))
libgame=makelib(target='game', source=Glob('game/*.cc'))
libmisc=makelib(target='misc', source=Glob('misc/*.cc'), LIBS=['curl'])
libobj=makelib(target='obj', source=Glob('obj/*.cc'))
libspec=makelib(target='spec', source=Glob('spec/*.cc'))
libtask=makelib(target='task', source=Glob('task/*.cc'))
if dbdriver == 'sqlite':
  libsys=makelib(target='sys', source=Glob('sys/*.cc'), LIBS=['sqlite3'], CXXFLAGS=cxxflags)
else:
  libsys=makelib(target='sys', source=Glob('sys/*.cc'), LIBS=[], CXXFLAGS=cxxflags)

libs=[libsys, libmisc, libcmd, libdisc, libgame,
      libobj, libspec, libtask, 'boost_program_options', 'boost_regex']

if twitter:
  libs.append('curl')

if twitter:
  libs.append('curl')
if dbdriver == 'mysql':
  libs.append('mysqlclient')
elif dbdriver == 'sqlite':
  libs.append('sqlite3')

# main binary
sneezy=env.Program('sneezy', 'main.cc', LIBS=libs)
env.InstallAs('../sneezy', sneezy)

# low tools
lto=env.Object('low/lowtools.cc');

amap=env.Program(['low/amap.cc', lto], LIBS=libs)
sqladdmobs=env.Program(['low/sqladdmobs.cc', lto], LIBS=libs)
sqladdobjs=env.Program(['low/sqladdobjs.cc', lto], LIBS=libs)
sqladdresp=env.Program(['low/sqladdresp.cc', lto], LIBS=libs)
sqladdwld=env.Program(['low/sqladdwld.cc', lto], LIBS=libs)
sqledimmobj=env.Program(['low/sqledimmobj.cc', lto], LIBS=libs)
sqledmob=env.Program(['low/sqledmob.cc', lto], LIBS=libs)
sqledobj=env.Program(['low/sqledobj.cc', lto], LIBS=libs)
sqledresp=env.Program(['low/sqledresp.cc', lto], LIBS=libs)
sqledshop=env.Program(['low/sqledshop.cc', lto], LIBS=libs)
sqledwld=env.Program(['low/sqledwld.cc', lto], LIBS=libs)

env.Install('../lowtools', [amap, sqladdmobs, sqladdobjs, sqladdresp,
                            sqladdwld, sqledimmobj, sqledmob, sqledobj,
                            sqledresp, sqledshop, sqledwld])
env.Alias('lowtools', '../lowtools')

# shell tools
econ=env.Program(['shell/econ.cc'], LIBS=libs)

env.Install('../shell', [econ])
env.Alias('shell', '../shell')


# unit tests
env.SConscript('tests/SConscript',
               exports='libs')
